package com.marceloaleixo.treinoflow.controller;
import com.marceloaleixo.treinoflow.entity.*; import com.marceloaleixo.treinoflow.enums.StatusAssinatura; import com.marceloaleixo.treinoflow.repository.*; import com.marceloaleixo.treinoflow.service.AssinaturaService; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.web.bind.annotation.*; import org.springframework.web.servlet.mvc.support.RedirectAttributes; import java.time.LocalDate;
@Controller @RequestMapping("/admin/assinaturas") public class AssinaturaAdminController{
 private final AssinaturaRepository assinaturas; private final UsuarioPersonalRepository personais; private final PlanoRepository planos; private final AssinaturaService service;
 public AssinaturaAdminController(AssinaturaRepository a,UsuarioPersonalRepository p,PlanoRepository pl,AssinaturaService s){assinaturas=a;personais=p;planos=pl;service=s;}
 @GetMapping public String lista(Model m){service.atualizarVencidas();m.addAttribute("assinaturas",assinaturas.findAllByOrderByDataVencimentoAsc());m.addAttribute("status",StatusAssinatura.values());return "admin/assinaturas/lista";}
 @GetMapping("/nova/{personalId}") public String nova(@PathVariable Long personalId,Model m){Assinatura a=new Assinatura();UsuarioPersonal p=personais.findByIdComPlano(personalId).orElseThrow();a.setPersonal(p);a.setPlano(p.getPlano());a.setDataInicio(LocalDate.now());a.setStatus(StatusAssinatura.ATIVA);m.addAttribute("assinatura",a);m.addAttribute("personais",personais.findAllComPlano().stream().filter(x->"PERSONAL".equals(x.getPerfil())).toList());m.addAttribute("planos",planos.findAll());m.addAttribute("status",StatusAssinatura.values());return "admin/assinaturas/form";}
 @GetMapping("/{id}/editar") public String editar(@PathVariable Long id,Model m){m.addAttribute("assinatura",assinaturas.findById(id).orElseThrow());m.addAttribute("personais",personais.findAllComPlano().stream().filter(x->"PERSONAL".equals(x.getPerfil())).toList());m.addAttribute("planos",planos.findAll());m.addAttribute("status",StatusAssinatura.values());return "admin/assinaturas/form";}
 @PostMapping("/salvar") public String salvar(@RequestParam(required=false) Long id,@RequestParam Long personalId,@RequestParam Long planoId,@RequestParam StatusAssinatura status,@RequestParam LocalDate dataInicio,@RequestParam(required=false) LocalDate dataVencimento,@RequestParam(required=false) LocalDate dataProximaCobranca,@RequestParam(required=false) LocalDate dataCancelamento,@RequestParam(required=false) String observacao,RedirectAttributes ra){service.salvar(id,personalId,planoId,status,dataInicio,dataVencimento,dataProximaCobranca,dataCancelamento,observacao);ra.addFlashAttribute("sucesso","Assinatura salva com sucesso.");return "redirect:/admin/assinaturas";}
}
